# -*- coding: utf-8 -*-
"""proyecto_gestion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19s83aKhYYpI5OmU5TsyCOc5gLqO2KpEK
"""

import re
import numpy as np
import pandas as pd
import scipy.sparse as sp
from collections import Counter

from sklearn.feature_extraction.text import TfidfVectorizer, ENGLISH_STOP_WORDS
from sklearn.cluster import MiniBatchKMeans
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler

from sentence_transformers import SentenceTransformer
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Dispositivo: {device}")
if device == "cuda":
    print(f"GPU: {torch.cuda.get_device_name(0)}")

df = pd.read_csv("dataset.csv")
df["hour"] = pd.to_datetime(df["time"], format="%H:%M", errors="coerce").dt.hour

user_messages = df.groupby("author")["text"].apply(list).to_dict()

with open("pan12-sexual-predator-identification-training-corpus-predators-2012-05-01.txt") as f:
    predators = set(line.strip() for line in f)

user_ids   = list(user_messages.keys())
all_labels = [1 if u in predators else 0 for u in user_ids]

print(f"Total usuarios : {len(user_ids)}")
print(f"Predadores     : {sum(all_labels)}")
print(f"Desbalance     : 1:{int(len(user_ids)/max(sum(all_labels),1))}")

def clean_text(text, keep_numbers=True):
    text = str(text).lower()
    text = re.sub(r"<.*?>", "", text)
    pattern = r"[^a-z0-9\s]" if keep_numbers else r"[^a-z\s]"
    return re.sub(pattern, "", text).strip()

pred_words, non_pred_words = [], []
for user, msgs in user_messages.items():
    tokens = [w for msg in msgs for w in clean_text(msg).split()
              if w not in ENGLISH_STOP_WORDS and len(w) > 2]
    (pred_words if user in predators else non_pred_words).extend(tokens)

pred_counts     = Counter(pred_words)
non_pred_counts = Counter(non_pred_words)
total_pred      = max(sum(pred_counts.values()), 1)
total_non_pred  = max(sum(non_pred_counts.values()), 1)

important_words = sorted(
    {w: (pred_counts[w] / total_pred) / max(non_pred_counts[w] / total_non_pred, 1e-9)
     for w in pred_counts if pred_counts[w] >= 10}.items(),
    key=lambda x: x[1], reverse=True
)
print("\nPalabras más distintivas de predadores:")
print(important_words[:50])

print("\nGenerando embeddings para clustering...")

model_st = SentenceTransformer("all-MiniLM-L6-v2", device=device)

all_texts_cluster = [" ".join(str(m) for m in user_messages[u][:50]) for u in user_ids]

embeddings = model_st.encode(
    all_texts_cluster,
    show_progress_bar=True,
    batch_size=512,
    device=device
)

kmeans = MiniBatchKMeans(n_clusters=20, random_state=42, batch_size=2000)
labels_cluster = kmeans.fit_predict(embeddings)

print("\nComposición por cluster:")
clusters = {}
for uid, label in zip(user_ids, labels_cluster):
    clusters.setdefault(label, []).append(uid)
for k, uids in sorted(clusters.items()):
    n_pred = sum(1 for u in uids if u in predators)
    print(f"  Cluster {k:2d}: {len(uids):5d} usuarios | {n_pred:3d} predadores ({100*n_pred/len(uids):.1f}%)")

all_texts_clf = [" ".join(str(m) for m in user_messages[u][:50]) for u in user_ids]
vec_clf = TfidfVectorizer(max_features=5000, stop_words="english")
X_tfidf = vec_clf.fit_transform(all_texts_clf)


X_embeddings = embeddings

df_feats = df.groupby("author").agg(
    n_messages     = ("text", "count"),
    avg_msg_length = ("text", lambda x: x.str.len().mean()),
    unique_convs   = ("conversation_id", "nunique"),
    avg_hour       = ("hour", "mean"),
    night_ratio    = ("hour", lambda x: (x >= 22).mean()),
    max_msg_length = ("text", lambda x: x.str.len().max()),
).fillna(0).reindex(user_ids).fillna(0)

scaler  = StandardScaler()
X_behav = scaler.fit_transform(df_feats)

X_combined = sp.hstack([
    X_tfidf,
    sp.csr_matrix(X_embeddings),
    sp.csr_matrix(X_behav)
])

print(f"\nShape final de features: {X_combined.shape}")

X_train, X_test, y_train, y_test = train_test_split(
    X_combined, all_labels,
    test_size=0.2, random_state=42, stratify=all_labels
)

clf = LogisticRegression(class_weight="balanced", max_iter=1000)
clf.fit(X_train, y_train)

print("\n── Resultados ──────────────────────────────────────────")
print(classification_report(y_test, clf.predict(X_test),
      target_names=["normal", "predador"]))

print("── Validación cruzada (5-fold) ─────────────────────────")
cv     = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
recall = cross_val_score(clf, X_combined, all_labels, cv=cv, scoring="recall")
prec   = cross_val_score(clf, X_combined, all_labels, cv=cv, scoring="precision")

print(f"Recall    : {recall.mean():.2f} ± {recall.std():.2f}")
print(f"Precision : {prec.mean():.2f} ± {prec.std():.2f}")

feature_names = (
    list(vec_clf.get_feature_names_out()) +
    [f"emb_{i}" for i in range(X_embeddings.shape[1])] +
    list(df_feats.columns)
)

coefs = pd.Series(clf.coef_[0], index=feature_names)

print("\n── Top 15 features PRO predador ────────────────────────")
print(coefs.sort_values(ascending=False).head(15))

print("\n── Top 5 features CONTRA predador ─────────────────────")
print(coefs.sort_values(ascending=True).head(5))

y_pred    = clf.predict(X_test)
test_ids  = [user_ids[i] for i in range(len(user_ids)) if i >= int(len(user_ids)*0.8)]

fn = [uid for uid, yt, yp in zip(test_ids, y_test, y_pred) if yt == 1 and yp == 0]
fp = [uid for uid, yt, yp in zip(test_ids, y_test, y_pred) if yt == 0 and yp == 1]

print(f"\nPredadores NO detectados (falsos negativos): {len(fn)}")
print(f"Falsas alarmas (falsos positivos)          : {len(fp)}")